// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Decision struct {
	ActorUserID     string    `json:"actorUserId"`
	RecipientUserID string    `json:"recipientUserId"`
	Liked           bool      `json:"liked"`
	CreatedAt       time.Time `json:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
}
