// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CountLikers(ctx context.Context, recipientUserID string) (int64, error)
	ListLikers(ctx context.Context, arg ListLikersParams) ([]ListLikersRow, error)
	ListNewLikers(ctx context.Context, arg ListNewLikersParams) ([]ListNewLikersRow, error)
	PutDecision(ctx context.Context, arg PutDecisionParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
